export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const CLEAR_REGISTER_USER_SUCCESS = "CLEAR_REGISTER_USER_SUCCESS"
export const OTP_VERIFICATION_SUCCESS = "OTP_VERIFICATION_SUCCESS"

export const GENERIC_REQUEST_FAILED = "GENERIC_REQUEST_FAILED"
export const GENERIC_REQUEST_FAILED_CLEAR = "GENERIC_REQUEST_FAILED_CLEAR"